#!/bin/bash

echo "Welcome to Lightweight Database UI Management (Adminer for PHP) Setup on LEMP Stack Setup (Ubuntu 16.04)"

echo "Steap:1 [System Update]"
echo "Update Starts....."
sudo yum update
echo -e "System Update Completed Successfully\n"

echo -e "Downloading latest Adminer\n"
cd /var/www/html
sudo wget -q -O db.php https://www.adminer.org/latest-en.php
echo -e "Dowloaded and Renamed Successfully\n"

echo "Creating a Configuration File for Adminer in sites-enabled directory"
cd /etc/httpd/conf.d/
sudo wget https://raw.githubusercontent.com/masiur/Environment-Configuration/master/src/adminer_centos_apache.conf
sudo systemctl restart httpd
cd ~
PUBLIC_IP=`wget http://ipecho.net/plain -O - -q ; echo`
echo "Configuration File Ready. visit http://$PUBLIC_IP:9999"

